name: example
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.29.0'

dependencies:
  cupertino_icons: ^1.0.5
  float_column: ^4.0.2
  flutter:
    sdk: flutter
  selectable:
    path: ../

dev_dependencies:
  flutter_lints_plus: ^3.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
